[package]
name = "adder_agent"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.17.2"
ic-cdk-timers = "0.6.0"
ic-llm = "1.0.1"
candid = "0.10.0"
serde_json = "1.0"
